# Generated by Django 4.2.10 on 2024-02-17 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_merge_0004_rebuilderdstatus_build_id_0004_soname"),
        ("packages", "0002_flagdenylist"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageNote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(db_index=True, editable=False)),
                ("pkgbase", models.CharField(db_index=True, max_length=255)),
                ("pkgver", models.CharField(max_length=255)),
                ("pkgrel", models.CharField(max_length=255)),
                ("epoch", models.PositiveIntegerField(default=0)),
                (
                    "num_packages",
                    models.PositiveIntegerField(
                        default=1, verbose_name="number of packages"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="message to user")),
                (
                    "repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.repo"
                    ),
                ),
            ],
            options={
                "get_latest_by": "created",
            },
        ),
    ]
